language: node_js
node_js:
  - 'iojs'
  - '0.12'
  - '0.10'
  - '0.8'
before_install:
  - node -e 'process.exit(/^v0\.8\./.test(process.version)?0:1)' && npm install -g npm || echo Not using v0.8.x
script: npm test
