build: off
version: '{build}'
skip_tags: true
clone_depth: 1
pull_requests:
  do_not_increment_build_number: true

platform:
  - x86
  - x64

environment:
  matrix:
    - nodejs_version: '5'
    - nodejs_version: '0.12'

install:
  - ps: Install-Product node $env:nodejs_version $env:platform
  - node --version
  - npm --version
  - npm install

test_script:
  - npm test
